### ISSUE TITLE
Good news everybody!

### ISSUE THREAD

**Issue by sledgehammer999** [qbittorrent/qbittorrrent-website#1]
@Chocobo1 I made you admin for this new repo. You can manage PRs, bugs, new members/admins.
If you don't want to be admin then tell me.

I am also tagging @qbittorrent/qbittorrent-frequent-contributors to take notice of this new repo.

@buinsky will probably be interested and might want write access. @Chocobo1 feel free to manage it accordingly.

FYI, the site has moved to a non-sf.net server. And we now support HTTPS by "Let's Encrypt". The server is run by shiki(forum's overlord). He will use a script to check for updates in the repo and then pull+publish them.

**Comment by Chocobo1** [comment]
This is great news indeed!
Thanks for your trust :)

@sledgehammer999 
Do you have any ideas/plans about the website? (Redesign or just fixups)

@ngosang, @buinsky
If you guys are interested, just leave a message, I can really use some help.

**Comment by buinsky** [comment]
Basically I'm not a web developer. I don't think I can help by anything.

**Comment by sledgehammer999** [comment]
@buinsky but you do a lot of webui fixes!!!

@Chocobo1 I don't mind redesigning the site. But try to keep links the same. For example links to news/donate/etc should exist in the new site too.

**Comment by ngosang** [comment]
This is a really good idea. If you need help just quote me and wait 2 or 3 days.

**Comment by Chocobo1** [comment]
@ngosang @buinsky
You now have write access, feel free to help moderate this repo.

**Comment by sledgehammer999** [comment]
Remember, master is a hot branch. It gets synced to the webserver automatically. So don't push non-working commits or redesigns to it. A separate branch should be used for that first and once consensus is reached that branch can be merged into master.
