### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by Chocobo1** [qbittorrent/qbittorrrent-website#6]
Hmmm, I'm seeing the website is often down, what happened?

Maybe it's possible to utilize CDN, e.g. cloudflare.

**Comment by ngosang** [comment]
It's working for me.

**Comment by sledgehammer999** [comment]
It working again. I had talked with the admin. It isn't because we are low in resources. He's just working some kinks on the server by his. Software weird issues. I'll keep in mind cloudflare if he thinks that the server can't take it.
