### ISSUE TITLE
Rename Repository

### ISSUE THREAD

**Issue by ngosang** [qbittorrent/qBittorrrent-website#7]
@sledgehammer999 Could you rename the repository from "qbittorrrent-website" to "qBittorrrent-website"?

**Comment by Chocobo1** [comment]
Strictly speaking it should be q**B**ittorrent/q**B**ittorrrent-website, LOL

**Comment by sledgehammer999** [comment]
I change the repo name with the correct capitalization. However, I'll keep the old name for the organization (aka "qbittorrent").

**Comment by funkydude** [comment]
Am I the only one that noticed the three `R` in torrrent?

**Comment by sledgehammer999** [comment]
@funkydude LOL. Fixed.

@Balls0fSteel please check your script. My fix changed the repo name.

**Comment by Balls0fSteel** [comment]
@sledgehammer999 It seems like capitalization has no effect whatsoever on Git checkout urls. I think Github converts the URL to lowercase or something (if it's even case sensitive.) So everything should be A-OK.

Sorry for the delay!

**Comment by sledgehammer999** [comment]
@Balls0fSteel capitalization was the first rename. Yesterday, I removed an extra `t` char from the name. (it was qBitt*t*orrent)

**Comment by Balls0fSteel** [comment]
Thanks to my slow reaction time I totally missed that change. 👍 
The script only fires off if the checkout is complete. (ret val is 0)

Otherwise nothing will happen.

**Comment by sledgehammer999** [comment]
Then you might want to update your local git repo to track the new URL for updates.
So run `git remote -v`. See the "fetch" url for the origin remote.
If it is wrong then do `git remote set-url origin <new-url>`
